Translation/guide/keras.md
xitu/tensorflow-docs pull request #101
Opened 2018-10-12 16:33 UTC by zhusimaji

#93

2018-10-16 18:50 UTC, lsvih commented
认领校对

2018-10-16 19:07 UTC, lsvih requested changes
需要修改部分格式

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +Keras 是一个用于构建和训练深度学习模型的高级程序接口。它被应用与快速原型设计，高级研究和生产环境，依赖于三大核心优势：
与 -> 于

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +Keras 是一个用于构建和训练深度学习模型的高级程序接口。它被应用与快速原型设计，高级研究和生产环境，依赖于三大核心优势：
依赖于 -> 有着

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +`tf.keras` 是 [Keras 接口规范](https://keras.io){:.external} 的 TensorFlow 实现。这是一个用于构建和训练模型的高级接口，其中包括对 TensorFlow 特定功能的一流支持，比如 [Eager execution](#eager_execution),
最后的英文逗号改中文顿号

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* 当 [保存模型权重](#weights_only)，`tf.keras` 默认 [检查点格式](./checkpoints.md)。传参 `save_format='h5'` 使用 HDF5 文件格式。
当 [保存模型权重](#weights_only) -> 当[保存模型权重](#weights_only)时

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* 当 [保存模型权重](#weights_only)，`tf.keras` 默认 [检查点格式](./checkpoints.md)。传参 `save_format='h5'` 使用 HDF5 文件格式。
默认 [检查点格式 中文间不需要空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +在 Keras 中, 你可以拼接 *网络层* 来构建 *模型*。模型（通常）是包含多个网络层的图。最常见的模型就是一堆网络层：`tf.keras.Sequential` 模型。
[斜体改粗体](https://github.com/xitu/gold-miner/wiki/译文排版规则指北#斜体文字使用加粗样式代替)

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +在 Keras 中, 你可以拼接 *网络层* 来构建 *模型*。模型（通常）是包含多个网络层的图。最常见的模型就是一堆网络层：`tf.keras.Sequential` 模型。
最常见的模型就是一堆网络层： -> 最常见的模型就是由多个网络层堆叠而成的：

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +# 模型中添加包含64个节点的稠密连接层：
稠密连接层 -> 全连接层

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +# 添加包含10个节点 softmax 层：
添加包含10个节点 softmax 层：
->
添加包含 10 个输出单元的 softmax 层：

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `activation`：设置网络层的激活函数。Set the activation function for the layer。此参数由内置函数或可调用对象指定。默认情况下，不应用任何激活函数。
英文删去

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `kernel_initializer` and `bias_initializer`：初始化网络层的权重（核和偏差）。该参数是一个名字或者可调用对象。默认是 `"Glorot uniform"` 初始值。
and -> 与

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `kernel_regularizer` and `bias_regularizer`：正则化方案应用于网络层的权重（核和偏差），比如 L1 和 L2 正则化。默认不适用任何正则化。
and -> 与

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `kernel_regularizer` and `bias_regularizer`：正则化方案应用于网络层的权重（核和偏差），比如 L1 和 L2 正则化。默认不适用任何正则化。
正则化方案应用于 -> 将正则化方案应用于

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `kernel_regularizer` and `bias_regularizer`：正则化方案应用于网络层的权重（核和偏差），比如 L1 和 L2 正则化。默认不适用任何正则化。
不适用 -> 不使用

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +# 将L1正则化因子为 0.01 的线性层应用于核矩阵：
L1 两边空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +# 将L1正则化因子为 0.01 的线性层应用于偏差向量：
L1 两边空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `optimizer`: 这个参数指定训练过程。从 `tf.train` 传递优化器实例，比如 [`Adam优化器`](/api_docs/python/tf/train/AdamOptimizer)，[`RMSProp优化器`](/api_docs/python/tf/train/RMSPropOptimizer) 或者 [`梯度下降优化器`](/api_docs/python/tf/tr
Adam RMSProp 中英文间空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `batch_size`：当传递 NumPy 数据时，模型将数据分成较小的批次，并在训练期间迭代这些批次。 此整数指定每个批次的大小。请注意，如果样本总数不能被批次大小整除，则最后一批可能会更小。
句号后多了个空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +使用 [数据集接口](./datasets.md) 扩展到大型数据集或者多设备训练。传递 `tf.data.Dataset` 实例 `fit` 方法：
中文间无需空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +使用 [数据集接口](./datasets.md) 扩展到大型数据集或者多设备训练。传递 `tf.data.Dataset` 实例 `fit` 方法：
传递 `tf.data.Dataset` 实例 `fit` 方法：
->
将 `tf.data.Dataset` 实例传递给 `fit` 方法：

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +*评估* 在提供的数据集上的代价损失和指标：
斜体改粗体

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +并且 *预测* 提供的 NumPy 数据在最后一层输出结果：
斜体改粗体

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +* `build`：创建网络层的权重。 使用 `add_weight` 方法添加权重。
句号后多了空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +# 训练 5 个epochs.
个epochs.
->
个 epoch。

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +通过 `tf.keras.estimator.model_to_estimator` 将 `tf.keras.Model` 转化为   `tf.estimator.Estimator` 对象，使用 `tf.estimator` 接口训练。详见 [从 Keras 模型中创建估计器](./estimators.md#creating_estimators_from_keras_models).
中文间无需空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +[估计器](./estimators.md) 接口可以用于分布式环境的训练模型。应用对象主要是工业界，例如可以导出模型进行生产的大型数据集的分布式训练。
中文间无需空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +通过 `tf.keras.estimator.model_to_estimator` 将 `tf.keras.Model` 转化为   `tf.estimator.Estimator` 对象，使用 `tf.estimator` 接口训练。详见 [从 Keras 模型中创建估计器](./estimators.md#creating_estimators_from_keras_models).
转化为 后面空格多了

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +注意： 开启 [eager execution](./eager.md) 可以调试 [估计器输入函数](./premade_estimators.md#create_input_functions) 和 观察数据。
冒号后空格多了，中文间无需空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +可以使用 `tf.contrib.distribute.DistributionStrategy` 在多个GPU上运行。 此接口在多个GPU上提供分布式训练，几乎不需要对现有代码进行任何更改。
句号后空格多了

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +可以使用 `tf.contrib.distribute.DistributionStrategy` 在多个GPU上运行。 此接口在多个GPU上提供分布式训练，几乎不需要对现有代码进行任何更改。
GPU 中英文间需要空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +定义 *输入管道*。`input_fn` 返回一个 `tf.data.Dataset` 对象，用于在多个设备之间分配数据 — 每个设备处理一个批处理输入分片。
斜体改粗体，中文间无需空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +以下示例在单个计算机上的多个GPU之间分发 `tf.keras.Model`。
中英文空格

2018-10-16 19:07 UTC, lsvih commented on guide/keras.md
> +目前，`tf.contrib.distribute.MirroredStrategy` 是唯一受支持的分发策略。 `MirroredStrategy` 使用 all-reduce 在一台机器上进行图模型内部的复制与同步。 要使用 Keras 的 `DistributionStrategy`，将 `tf.keras.Model` 转换为`tf.estimator.Estimator` 与 `tf.
句号后空格多了

2018-10-17 00:46 UTC, zhusimaji commented
@lsvih  谢谢提出的意见，这个晚上我回去得好好改改了

2018-10-17 16:56 UTC, rocheers commented
@leviding 校对认领

2018-10-17 17:24 UTC, rocheers commented on guide/keras.md
> +* `tf.keras` 版本在最新的 TensorFlow 发布中可能和 PyPI 中最新的 `keras` 版本不一样。请检查 `tf.keras.__version__`。
「`tf.keras` 版本在最新的 TensorFlow 发布中可能和 PyPI 中最新的 `keras` 版本不一样。」=》「在 TensorFlow 最新发布的版本中，`tf.keras` 的版本可能和 PyPI 中 `keras` 最新的版本不一样」

2018-10-17 17:29 UTC, rocheers commented on guide/keras.md
> +* 当[保存模型权重](#weights_only)，`tf.keras` 默认[检查点格式](./checkpoints.md)。传参 `save_format='h5'` 使用 HDF5 文件格式。
「传参 `save_format='h5'` 使用 HDF5 文件格式。」=>「将 `save_format='h5'` 作为参数传入，以使用 HDF5 文件格式。」

2018-10-17 17:35 UTC, rocheers commented on guide/keras.md
> +- *用户友好*<br>
[斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)
下面的两个副标题有同样的问题。

2018-10-18 14:53 UTC, zhusimaji commented
@rocheers @leviding  已经根据校对意见修改

2018-10-18 15:20 UTC, lsvih approved these changes

2018-10-18 17:42 UTC, rocheers reviewed
@leviding @zhusimaji 校对完了，有几处格式排版错误，还有几处个人认为不太通顺的地方，请斟酌。

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +# 模型中添加包含64个节点的全连接层：
[中文与数字之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E6%96%87%E4%B8%8E%E6%95%B0%E5%AD%97%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)
[数字与单位之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%95%B0%E5%AD%97%E4%B8%8E%E5%8D%95%E4%BD%8D%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +* `kernel_regularizer` 与 `bias_regularizer`：将正则化方案应用于网络层的权重（核和偏差），比如 L1 和 L2 正则化。默认不使用任何正则化。
「比如 L1 和 L2 正则化」=>「比如 L1 或 L2 正则化」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +* `optimizer`: 这个参数指定训练过程。从 `tf.train` 传递优化器实例，比如 [`Adam 优化器`](/api_docs/python/tf/train/AdamOptimizer)，[`RMSProp 优化器`](/api_docs/python/tf/train/RMSPropOptimizer) 或者 [`梯度下降优化器`](/api_docs/python/tf/
「从 `tf.train` 传递优化器实例」=>「从 `tf.train` 模块传递优化器实例」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +<b>评估</b>在提供的数据集上的代价损失和指标：
「<b>评估</b>在提供的数据集上的代价损失和指标」=>「对提供的数据，<b>评估</b>推断模式下的代价损失和指标」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +并且<b>预测</b>提供的 NumPy 数据在最后一层输出结果：
「并且<b>预测</b>提供的 NumPy 数据在最后一层输出结果」=>「并且作为 NumPy 数组，对提供的数据，预测在推断模式下最后一层的输出」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +当 [Eager execution](./eager.md) 被启用时，对子类化模型特别有用，因为可以强制写入前向传播。
「对子类化模型特别有用」=>「模型子类化特别有用」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +* `tf.keras.callbacks.EarlyStopping`：当验证上表现停止增长时终端训练。
「当验证上表现停止增长时终端训练」=>「当验证性能停止增长时，中断训练」

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +可以保存模型的配置 — 这可以在没有任何权重的情况下序列化模型体系结构。即使没有定义原始模型的代码，保存的配置也可以重新创建和初始化相同的模型。
少翻译最后一句话。「Keras supports JSON and YAML serialization formats:」=>『Keras 支持 JSON 和 YAML 序列化格式』

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +[Eager execution](./eager.md) 是一个命令式编程环境，可立即评估操作。这不是Keras所必需的，但是 `tf.keras` 支持，对于检查程序和调试很有用。
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)
『这不是Keras所必需的』=>『这不是 Keras 所必需的』

2018-10-18 17:42 UTC, rocheers commented on guide/keras.md
> +所有 `tf.keras` 模型构建接口都与 eager execution 兼容。虽然可以使用 `Sequential`和函数式接口，但是 eager execution 对 *子类化模型* 和构建 *自定义层* 有特别友好 — 仅需要您编写前向传播的接口代码（而不是使用现有的创建模型的接口）。
1. [斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)
2. 『虽然可以使用 `Sequential`和函数式接口』 => 『虽然可以使用 `Sequential` 和函数式接口』，英文后面少了一个空格

2018-10-19 02:13 UTC, leviding commented
@zhusimaji 可以修改了

2018-10-19 14:44 UTC, zhusimaji commented on guide/keras.md
> +* `kernel_regularizer` 与 `bias_regularizer`：将正则化方案应用于网络层的权重（核和偏差），比如 L1 和 L2 正则化。默认不使用任何正则化。
正则化有单独使用L1/ L2其中一个，也有同时使用的，所以在此区别不大

2018-10-19 14:44 UTC, zhusimaji commented on guide/keras.md
> +<b>评估</b>在提供的数据集上的代价损失和指标：
推断模式的直译在此觉得不太通顺

2018-10-19 14:45 UTC, zhusimaji commented on guide/keras.md
> +并且<b>预测</b>提供的 NumPy 数据在最后一层输出结果：
同上--推断模式的直译觉得不太好理解

2018-10-19 14:55 UTC, zhusimaji commented
@leviding  @rocheers 已经根据最新的校对意见修改了

2018-10-20 03:09 UTC, leviding approved these changes

2018-10-20 03:11 UTC, merged